version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    target-branch: main
    reviewers:
      - byu-oit/specops-developer

  # NPM Dependencies
  - package-ecosystem: npm
    directory: "/lambda"
    schedule:
      interval: monthly
    target-branch: main
    reviewers:
      - byu-oit/specops-developer
