name: CI

on:
  pull_request:
    branches: [main]
env:
  tf_working_dir: "./examples/ci"
  lambda_working_dir: "./lambda"
  aws_key_name: byu_oit_terraform_dev_key
  aws_secret_name: byu_oit_terraform_dev_secret

jobs:
  check:
    name: Run All Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install
        working-directory: ${{ env.lambda_working_dir }}
        run: npm ci

      - name: linting
        working-directory: ${{ env.lambda_working_dir }}
        run: npm run lint

      - name: build
        working-directory: ${{ env.lambda_working_dir }}
        run: npm run build

      - name: tests
        working-directory: ${{ env.lambda_working_dir }}
        run: npm run test:coverage

  format:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.1.x'

      - name: Terraform Format
        working-directory: "./"
        run: terraform fmt -check -recursive

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: ['0.14.x', '0.15.x', '1.0.x', '1.1.x', '1.2.x']
      fail-fast: false
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[env.aws_key_name] }}
          aws-secret-access-key: ${{ secrets[env.aws_secret_name] }}
          aws-region: us-west-2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}

      - name: Terraform Init
        working-directory: ${{ env.tf_working_dir }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.tf_working_dir }}
        run: terraform plan.tfplan -var 'humio_token=fake-token' -input=false -out=plan.tfplan

      - name: Comment Terraform Plan
        uses: byu-oit/github-action-tf-plan-comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ env.tf_working_dir }}
          terraform-plan-file: plan.tfplan

      - name: Analyze Terraform Plan
        uses: byu-oit/github-action-tf-plan-analyzer@v2
        with:
          divvycloud-username: ${{ secrets.DIVVYCLOUD_USERNAME }}
          divvycloud-password: ${{ secrets.DIVVYCLOUD_PASSWORD }}
          working-directory: ${{ env.tf_working_dir }}
          terraform-plan-file: plan.tfplan
