name: Publish

on:
  push:
    tags:
      - '*'

env:
  aws_key_name: 'byu_oit_terraform_prd_key'
  aws_secret_name: 'byu_oit_terraform_prd_secret'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set tag
        id: tag
        run: echo ::set-output name=value::"$GITHUB_REF" | sed 's/refs\/tags\/v\{0,1\}//'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[env.aws_key_name] }}
          aws-secret-access-key: ${{ secrets[env.aws_secret_name] }}
          aws-region: us-west-2

      - name: Log into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: lambda
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/humio-logger:${{ steps.tag.outputs.value }}
